# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# title      Circle CI Build Configuration                       +
# project    nord-highlightjs                                    +
# repository https://github.com/arcticicestudio/nord-highlightjs +
# author     Arctic Ice Studio                                   +
# email      development@arcticicestudio.com                     +
# copyright  Copyright (C) 2017                                  +
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# [References]
# Circle CI
#   https://circleci.com/docs
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.7
    steps:
      - checkout
      - run:
          name: install-global-gulp-cli
          command: sudo npm install -g gulp-cli
      - run:
          name: npm-install
          command: npm install
      - run:
          name: lint
          command: gulp --harmony lint
